create table if not exists public.imagens_rejeitadas (
  id bigint generated by default as identity primary key,
  noticia_id bigint not null references public.noticias(id) on delete cascade,
  image_url text not null,
  full_hash text,
  crop_hash text,
  criado_em timestamptz not null default now(),
  unique (noticia_id, image_url)
);

create index if not exists imagens_rejeitadas_noticia_id_idx
  on public.imagens_rejeitadas (noticia_id);

alter table public.imagens_rejeitadas enable row level security;
