create table if not exists public.wiregeek_tiktok_channels (
  slot text primary key,
  open_id text not null,
  display_name text not null,
  access_cipher text not null,
  refresh_cipher text not null,
  expires_at timestamptz,
  connected_at timestamptz not null default now()
);

create table if not exists public.wiregeek_tiktok_oauth (
  state_hash text primary key,
  session_hash text not null,
  verifier_cipher text not null,
  expires_at timestamptz not null
);

create table if not exists public.wiregeek_tiktok_uploads (
  id bigint generated by default as identity primary key,
  group_id uuid not null,
  slot text not null,
  open_id text not null,
  asset_sha256 text not null,
  status text not null default 'PREPARANDO',
  publish_id text,
  video_id text,
  metadata jsonb not null default '{}'::jsonb,
  bytes bigint not null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_id, slot)
);

create index if not exists wiregeek_tiktok_uploads_group_idx on public.wiregeek_tiktok_uploads (group_id);
alter table public.wiregeek_tiktok_channels enable row level security;
alter table public.wiregeek_tiktok_oauth enable row level security;
alter table public.wiregeek_tiktok_uploads enable row level security;
