
create table if not exists public.site_news (
  id bigint generated by default as identity primary key,
  origin text not null,
  external_id text not null,
  wiregeek_noticia_id bigint references public.noticias(id) on delete set null,
  slug text not null,
  category text not null,
  title text not null,
  short_title text,
  excerpt text,
  body text,
  highlight text,
  hashtags text[] not null default '{}'::text[],
  source_name text,
  source_url text,
  sources jsonb not null default '[]'::jsonb,
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  status text not null default 'published'
    check (status in ('draft', 'published', 'archived')),
  featured boolean not null default false,
  source_published_at timestamptz,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_news_origin_external_key unique (origin, external_id),
  constraint site_news_slug_key unique (slug)
);

alter table public.site_news enable row level security;

create unique index if not exists site_news_wiregeek_noticia_id_key
  on public.site_news (wiregeek_noticia_id)
  where wiregeek_noticia_id is not null;

create index if not exists site_news_status_published_at_idx
  on public.site_news (status, published_at desc);

create index if not exists site_news_category_published_at_idx
  on public.site_news (category, published_at desc);

create or replace function public.set_site_news_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_news_set_updated_at on public.site_news;

create trigger site_news_set_updated_at
before update on public.site_news
for each row
execute function public.set_site_news_updated_at();

grant select, insert, update, delete on table public.site_news to service_role;
grant usage, select on sequence public.site_news_id_seq to service_role;
;
